//
// Copyright (c) 2025 Regents of the SIGNET lab, University of Padova.
// All rights reserved.
//
// Initialization for uwreplicator library.
//
#include <tclcl.h>
#include <packet.h>

// No new packet type or header introduced; module only duplicates existing packets.
// Embedded Tcl defaults script symbol generated by tcl2cpp (see Makefile.am)
extern EmbeddedTcl uwreplicator_tcl;

extern "C" int Uwreplicator_Init()
{
	// Load default Tcl configuration (sets replicas_ and sapcing_ defaults and tag)
	uwreplicator_tcl.load();
	return 0;
}

extern "C" int Cyguwreplicator_Init()
{
	return Uwreplicator_Init();
}

